name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    environment: 'CYPRESS_DATABASE_URL'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Install NPM dependencies, cache them correctly
        # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_DATABASE_URL: ${{secrets.CYPRESS_DATABASE_URL}}
        with:
          component: true
          build: npm run build
          start: npm start
